POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "by stranger",
  "likes": 0
}

###

PUT http://localhost:3001/api/blogs/6149c1040a3f26a46dbbb49c
Content-Type: application/json

{
  "author": "new author",
  "likes": 1000
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "by stranger",
  "name": "hiasdf",
  "password": "ihsowieof"
}

###
